### ISSUE TITLE
Gem release

### ISSUE THREAD

**Issue by davekinkead** [karmi/tire-contrib#20]
@karmi - can you please publish the current master to ruby gems.

I was trying to get a project up & running and spent age wondering why

```
require 'tire/model/dynamic_persistence' 
```

couldn't be found.

Turns out https://rubygems.org/gems/tire-contrib hasn't been updated in over 12 months despite new code being pushed to master here.

Ta.

**Comment by karmi** [comment]
Hello, released as 0.1.2, changelog: https://github.com/karmi/tire-contrib/compare/v0.1.1...v0.1.2

(I somewhat lazily rely on people using the `git:` feature in Gemfile, sorry :)

**Comment by davekinkead** [comment]
Lovey!
